script: bundle exec bacon spec/*_spec.rb

language: ruby

rvm:
  - 2.4.0
  - 2.3.3
  - 1.8.7
  - ruby-head
  - ree
  - jruby-19mode # JRuby in 1.9 mode
  - rbx-19mode

matrix:
  allow_failures:
    - rvm: ruby-head
